name: Run new evals

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_evals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          # Install the package with core dependencies first
          pip install -e .

      - name: Run Recoup Evals
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Processing recoup"
          oaieval gpt-3.5-turbo recoup
